# My SQL Configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/CNPayment?createDatabaseIfNotExists=true
#    username: root
#    password: Sonu123@
#    driver-class: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate.ddl-auto: create-drop
#server:
#  port: 8060


# H2 Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testDb
    username: s2
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
server:
  port: 8060
     